name: AWS Terraform Apply

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_KEY_SECRET }}
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      with:
        DB_NAME: ${{ env.DB_NAME }}
        DB_USER: ${{ env.DB_USER }}
        PARAM_GROUP_NAME: ${{ env.PARAM_GROUP_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}